export default [
  {
    category: "Hedelmät ja vihannekset",
    color: 0,
    items: [
      {name: "appelsiini", checked: false},
      {name: "avokado", checked: false},
      {name: "banaanit", checked: false},
      {name: "chili", checked: false},
      {name: "omenat", checked: false},
      {name: "kirsikkatomaatit", checked: false},
      {name: "kukkakaali", checked: false},
      {name: "kurkku", checked: false},
      {name: "lime", checked: false},
      {name: "mandariinit", checked: false},
      {name: "paprika", checked: false},
      {name: "parsakaali", checked: false},
      {name: "porkkana", checked: false},
      {name: "punasipuli", checked: false},
      {name: "sipuli", checked: false},
      {name: "sitruuna", checked: false},
      {name: "tomaatit", checked: false},
      {name: "valkosipuli", checked: false},
    ],
  },
  {
    category: "Säilykkeet",
    color: 1,
    items: [
      {name: "ketsuppi", checked: false},
      {name: "kidneypavut", checked: false},
      {name: "majoneesi", checked: false},
      {name: "mustapavut", checked: false},
      {name: "oliivit", checked: false},
      {name: "tomaattimurska", checked: false},
      {name: "tomaattipyree", checked: false},
      {name: "tonnikala", checked: false},
    ],
  },
  {
    category: "Siivous",
    color: 3,
    items: [
      {name: "huuhteluaine", checked: false},
      {name: "konetiskiaine", checked: false},
      {name: "kumihanskat", checked: false},
      {name: "pyykinpesuaine", checked: false},
      {name: "pöytärätit", checked: false},
      {name: "tiskiaine", checked: false},
      {name: "tiskiharja", checked: false},
    ],
  },
  {
    category: "Hygienia",
    color: 4,
    items: [
      {name: "deodorantti", checked: false},
      {name: "hammasharja", checked: false},
      {name: "hammaslanka", checked: false},
      {name: "hammastahna", checked: false},
      {name: "hoitoaine", checked: false},
      {name: "kasvojenpesuaine", checked: false},
      {name: "käsisaippua", checked: false},
      {name: "laastarit", checked: false},
      {name: "rasva", checked: false},
      {name: "shampoo", checked: false},
      {name: "suihkusaippua", checked: false},
    ],
  },
  {
    category: "Maitotuotteet",
    color: 2,
    items: [
      {name: "cheddar", checked: false},
      {name: "jugurtti", checked: false},
      {name: "juusto", checked: false},
      {name: "maito", checked: false},
      {name: "mehu", checked: false},
      {name: "parmesan", checked: false},
      {name: "tuorejuusto", checked: false},
      {name: "turkkilainen jugurtti", checked: false},
    ],
  },
  {
    category: "Mausteet ja öljyt",
    color: 6,
    items: [
      {name: "basilika", checked: false},
      {name: "cayennepippuri", checked: false},
      {name: "chilijauhe", checked: false},
      {name: "korianteri", checked: false},
      {name: "mustapippuri", checked: false},
      {name: "oliiviöljy", checked: false},
      {name: "oregano", checked: false},
      {name: "paprika", checked: false},
      {name: "rypsiöljy", checked: false},
      {name: "seesamiöljy", checked: false},
      {name: "soija", checked: false},
      {name: "suola", checked: false},
      {name: "valkopippuri", checked: false},
      {name: "valkosipulijauhe", checked: false},
    ],
  },
  {
    category: "Muut",
    color: 7,
    items: [
      {name: "kananmunat", checked: false},
      {name: "kasvissosekeitto", checked: false},
      {name: "limu", checked: false},
      {name: "olut", checked: false},
      {name: "pasta", checked: false},
      {name: "purkka", checked: false},
      {name: "riisi", checked: false},
      {name: "smoothie", checked: false},
    ],
  },
  {
    category: "Pakasteet",
    color: 5,
    items: [
      {name: "hedelmäsekoitus", checked: false},
      {name: "jääpalat", checked: false},
      {name: "jäätelö", checked: false},
      {name: "mansikat", checked: false},
      {name: "marjasekoitus", checked: false},
      {name: "mehujäät", checked: false},
      {name: "pinaatti", checked: false},
      {name: "pizza", checked: false},
      {name: "wokkivihannekset", checked: false},
    ],
  },
];
