import { AsapCondensed_700Bold } from "@expo-google-fonts/asap-condensed";
import { StyleSheet, StatusBar } from "react-native";

export default editCategories = StyleSheet.create({
    devButtonsContainer: {
        paddingBottom: 50,
    },
    newCategoryContainer: {
        height: 80,
        marginBottom: 20,
    },
    newCategoryButton: {
        height: 80,
        backgroundColor: "rgba(255, 0, 0, 0)",
        justifyContent: "center",
        alignItems: "center",
        color: "#b75c2f",
        marginLeft: 20,
        marginBottom: 20,
        width: 200,
    },
    newCategoryRoundButton: {
        height: 30,
        width: 30,
        borderRadius: 100,
        alignItems: "center",
        justifyContent: "center",
        marginLeft: 0,
        backgroundColor: "#b75c2f",

    },
    newCategoryText: {
        color: "#b75c2f",
        alignItems: "center",
        justifyContent: "center",
        fontFamily: "AsapCondensed_700Bold",
        fontSize: 20,
        marginLeft: 10,
    },

    categoryHeaderContainer: {
        backgroundColor: "#545454",
        height: 40,
        flexDirection: "row",
        alignItems: "center",
        justifyContent: "space-between",
        marginVertical: 0,
    },
    categoryHeader: {
        marginLeft: 40,
        marginBottom: 4,
        fontFamily: "AsapCondensed_700Bold",
        fontSize: 22,
        textShadowColor: "rgba(0, 0, 0, 0.25)",
        textShadowOffset: { width: 2, height: 2 },
        textShadowRadius: 1,
        color: "#ffffff",
    },
    categoryHeaderSecondary: {
        flexDirection: "row",
        height: 40,
        backgroundColor: "rgba(0, 0, 0, 0.25)",
        justifyContent: "space-around",
        alignItems: "center",
        paddingHorizontal: 16,
    },
    headerButtons: {
        flexDirection: "row",
        color: "#fff",
        alignItems: "center",
    },
    headerButtonText: {
        marginLeft: 10,
        color: "#fff",
        fontFamily: "AsapCondensed_700Bold",
    },
    addItemContainer: {
        height: 30,
        flexDirection: "row",
        alignItems: "center",
        justifyContent: "space-between",
        paddingRight: 20,
        marginTop: 25,
        marginLeft: 30,
    },
    addItemTouchable: {
        flexDirection: "row",
        alignItems: "center",
    },
    addItemRoundButton: {
        height: 30,
        width: 30,
        borderRadius: 100,
        alignItems: "center",
        justifyContent: "center",
        marginLeft: 0,
    },
    addItemText: {
        alignItems: "center",
        justifyContent: "center",
        fontFamily: "AsapCondensed_700Bold",
        fontSize: 20,
        marginLeft: 10,
    },
    input: {
        flex: 5,
        width: "60%",
        height: "100%",
        borderBottomWidth: 1,
        borderBottomColor: "#757575",
        marginRight: 30,
        color: "#757575",
        fontFamily: "Lato_900Black",
        fontSize: 20,
        paddingLeft: 5,
    },
    buttonsContainer: {
        flex: 2,
        flexDirection: "row",
        justifyContent: "space-between",
    },
    addItemTextButton: {
        width: 70,
        flexDirection: "row",
        alignItems: "center",
        justifyContent: "center",
    },
    roundButton: {
        height: 40,
        width: 40,
        borderRadius: 100,
        alignItems: "center",
        justifyContent: "center",
    },
    disabledButton: {
        backgroundColor: "#ebebeb",
    },
    itemCheckbox: {
        backgroundColor: "#ebebeb",
        size: 10,
        borderWidth: 1,
        borderColor: "#9eb9c8",
    },
    editCategoryHeaderContainer: {
        backgroundColor: "#545454",
        height: 40,
        flexDirection: "row",
        alignItems: "center",
        justifyContent: "space-between",
        marginVertical: 0,
        paddingHorizontal: 10,
    },
    categoryHeaderInput: {
        flex: 1,
        paddingLeft: 10,
        marginRight: 10,
        fontFamily: "AsapCondensed_700Bold",
        fontSize: 22,
        textShadowColor: "rgba(0, 0, 0, 0.25)",
        textShadowOffset: { width: 2, height: 2 },
        textShadowRadius: 1,
        color: "#ffffff",
        backgroundColor: "rgba(255, 255, 255, 0.2)",
    },

});